name: Release minor version

on: workflow_dispatch

jobs:

  # bump up patch if dev release finished
  increment_minor_version:
    name: Increment minor version after release
    needs: release_dev
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MZMINE_BOT_ACTIONS_TOKEN }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle to increment version
        run: ./gradlew incrementMinor
      - name: Commit updated version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increment minor version
          branch: master

  # release stable version after version increment
  release_stable:
    name: Release new mzmine version
    needs: increment_minor_version
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4 # download all artifacts
        with:
          path: build/
      - name: Create stable release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN}}"
          prerelease: true
          title: "Release build"
          files: build/*/*


