name: macOS test sign

on: workflow_dispatch

jobs:

  # test build and sign macos
  macos-signed-build:
    name: Build signed macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 19.0.1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew --stacktrace --info

      # for macOS:
      # 1. upload the dmg installer
      # 2. remove the dmg isntaller from path
      # 3. zip and upload the jpackage directory
      # This is needed because zipping of the /jpackage/MZmine.app portable version zips the content
      # of the folder not the folder itself
      - name: Upload builds macos
        uses: actions/upload-artifact@v2
        with:
          name: MZmine_macos_dmg_installer
          path: build/jpackage/*.dmg
          retention-days: 7  # store for 7 days

      # Sign MZmine.app with ÄŒVUT developer ID
      - name: Codesign executable for MacOS
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo "$MACOS_CERTIFICATE" | base64 --decode > certificate.p12
          security create-keychain -p abc123 build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p abc123 build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k abc123 build.keychain
          /usr/bin/codesign --force --deep -s "Developer ID Application: Ceske vysoke uceni technicke v Praze (LK4H72N842)" build/jpackage/MZmine.app -v

      - name: Remove dmg File (which was already uploaded) and Make .app executable and zip it
        run: |
          find ./build/jpackage/ -name '*.dmg' -delete
          chmod a+x build/jpackage/MZmine.app/Contents/MacOS/MZmine
      - name: Zip portable macos
        uses: papeloto/action-zip@v1
        with:
          files: build/jpackage/
          dest: build/jpackage/MZmine_macOS_portable.zip
      - name: Upload macos portable builds
        uses: actions/upload-artifact@v2
        with:
          name: MZmine_macos_portable
          path: build/jpackage/MZmine_macOS_portable.zip
          retention-days: 7  # store for 7 days
